# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20160528_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
